#!/usr/bin/env bash
set -euo pipefail

# build_app.sh — compile RufusMac and assemble a portable RufusMac.app bundle.
# No Xcode required: uses the Swift Package Manager toolchain from Command Line Tools.
#
#   Usage: scripts/build_app.sh [debug|release]
#
# This fork ships Intel (x86_64) only — no Apple Silicon slice in the .app/.dmg.
# Minimum OS is macOS 14 (Liquid Glass at runtime on 26+; material fallback on 14/15).
# Building still needs a toolchain with the macOS 26 SDK for Liquid Glass symbols.
#
# Developed by Harith Dilshan / h4rithd.com — built with the help of Claude Code.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CONFIG="${1:-release}"
ARCH="x86_64"
APP_NAME="RufusMac"
BUNDLE_ID="com.h4rithd.rufusmac"
VERSION="$(cat "$ROOT/VERSION" 2>/dev/null || echo 0.1.0)"
BUILD_NUM="$(date +%Y%m%d%H%M)"

DIST="$ROOT/dist"
APP="$DIST/$APP_NAME.app"
MACOS_DIR="$APP/Contents/MacOS"
RES_DIR="$APP/Contents/Resources"

echo "▶ Building RufusMac ($CONFIG, $ARCH-only)…"
swift build -c "$CONFIG" --arch "$ARCH"
BIN_DIR="$(swift build -c "$CONFIG" --arch "$ARCH" --show-bin-path)"
BIN="$BIN_DIR/$APP_NAME"

# Refuse to ship a fat or wrong-arch binary.
ARCHS="$(lipo -archs "$BIN" 2>/dev/null || true)"
if [ "$ARCHS" != "$ARCH" ]; then
  echo "error: expected $ARCH-only binary, got: ${ARCHS:-unknown}" >&2
  exit 1
fi

echo "▶ Assembling $APP …"
rm -rf "$APP"
mkdir -p "$MACOS_DIR" "$RES_DIR"
cp "$BIN" "$MACOS_DIR/$APP_NAME"

# Copy any SPM resource bundles next to the executable.
shopt -s nullglob
for b in "$BIN_DIR"/*.bundle; do cp -R "$b" "$RES_DIR/"; done
shopt -u nullglob

# App icon (generated by scripts/make_icon.sh).
[ -f "$ROOT/Assets/AppIcon.icns" ] && cp "$ROOT/Assets/AppIcon.icns" "$RES_DIR/AppIcon.icns"

# Bundle third-party tools (wimlib, mke2fs, ventoy, uefi-ntfs) if fetched.
if [ -d "$ROOT/vendor" ] && [ -n "$(ls -A "$ROOT/vendor" 2>/dev/null)" ]; then
  mkdir -p "$RES_DIR/thirdparty"
  cp -R "$ROOT/vendor/." "$RES_DIR/thirdparty/"
  echo "  bundled third-party tools from vendor/"
fi

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>$APP_NAME</string>
  <key>CFBundleDisplayName</key><string>$APP_NAME</string>
  <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
  <key>CFBundleExecutable</key><string>$APP_NAME</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>$BUILD_NUM</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSApplicationCategoryType</key><string>public.app-category.utilities</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>NSHumanReadableCopyright</key><string>© Harith Dilshan — h4rithd.com · GPLv3</string>
</dict>
</plist>
PLIST

printf 'APPL????' > "$APP/Contents/PkgInfo"

echo "▶ Ad-hoc code signing…"
codesign --force --deep --sign - "$APP" >/dev/null 2>&1 && echo "  signed (ad-hoc)" || echo "  (codesign skipped)"

echo "✅ Built $APP  (v$VERSION build $BUILD_NUM)"
